name: AWS and Terraform/Terragrunt setup
description:  Composite action for setting up AWS credentials and Terraform/Terragrunt


inputs:
  aws-region: 
    description:
    required: true
  aws-account-id:
    description:
    required: true
  ssh-key-shared-modules:
    description: 
    required: true
  gh-pat: 
    description:
    required: true
  terraform-version:
    description: 
    required: false
    default: latest
  terragrunt-version: 
    description: 
    required: false
    default: latest

outputs:
  script:
    description: 
    value: "Done"


runs: 
  using: "composite"
  steps: 
    # - uses: actions/checkout@v3
    #   with:
    #     repository: awazevr/amazon-terraform-setup-action
    #     token: ${{ inputs.gh-pat }}
      
    - name: starting setup 
      shell: bash
      run: echo "Starting composite action"
    
    # # needs chmod +x for scripts
    # - name: bash script
    #   shell: bash
    #   run: bash/setup.sh
    #   id: setup-script

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github

    - run: aws sts get-caller-identity

    - name: Setup infra modules deploy key
      shell: bash
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.ssh_key_shared_modules }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{env.TERRAFORM_VERSION}}
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: latest

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: latest


